sources/_project_/urls.py
from django.views.decorators.cache import cache_page
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from product import sitemaps

sitemaps = {
    'product_home': sitemaps.HomeSitemap,
    'product_category': sitemaps.CategorySitemap,
    'product_product': sitemaps.ProductSitemap,
}

urlpatterns = [

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    url(r'^', include('product.urls', namespace='product')),
]

sources/product/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^products/recent/$', views.RecentListView.as_view(), name='recent_products'),
    url(r'^products/(?P<category_slug>[a-z0-9]+)/(?P<slug>[a-z0-9]+)/$',
        views.ProductDetailView.as_view(), name='product_detail'),
    url(r'^products/(?P<slug>[a-z0-9]+)/$', views.CategoryDetailView.as_view(),
        name='category_detail'),

    url(r'^products/$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^$', views.HomePageView.as_view(), name='home')
]

sources/product/models.py
from django.db import models
from django.core.urlresolvers import reverse

class BaseModel(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract= True

class Category(BaseModel):
    """Category model"""
    class Meta:
        ordering = ['name']
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse('product:category_detail', args=[self.slug])

    def __str__(self):
        return self.name

class Product(BaseModel):
    """Product model"""
    category = models.ForeignKey(Category, related_name='products')
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "products"

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.name

sources/product/views.py
from datetime import datetime, timedelta
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render, get_object_or_404, render_to_response
from django.core.paginator import EmptyPage, Paginator
from .models import Category, Product

from django.views.generic import ListView, DetailView, TemplateView


class RecentListView(ListView):
    model = Category

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(RecentListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        recent_date = datetime.today() - timedelta(days=1)
        return Category.objects.filter(created_at__gte=recent_date)


class CategoryListView(ListView):
    model = Category


class CategoryDetailView(DetailView):
    """Category detail view"""
    model = Category


class ProductDetailView(DetailView):
    """Product detail view"""
    model = Product
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])


class HomePageView(TemplateView):
    """Home page"""
    template_name = 'product/base.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        return context

sources/product/templates/product/_pagination.html
<div class="pagination">
    <span class="step-links">
        {% if items.has_previous and items.previous_page_number > 1 %}
            <a href="?page={{ items.previous_page_number }}">previous</a>
        {% elif items.previous_page_number == 1 and slug %}
            <a href="{% url url slug %}">previous</a>
        {% elif items.previous_page_number == 1 %}
            <a href="{% url url %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ items.number }} of {{ items.paginator.num_pages }}.
        </span>

        {% if items.has_next %}
            <a href="?page={{ items.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

sources/product/templates/product/_product_list.html
<div class="row">
    <ul>
        {% for product in products %}
            <div class="col-lg-12 col-md-12 col-sm-12">
                <li><a href="{{ product.get_absolute_url }}">{{ product.name }}</a> {{ product.price }} {{ product.created_at }}</li>
            </div>
        {% endfor %}
    </ul>
</div>

sources/product/templates/product/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <meta name="description" content="{% block description %}{% endblock %}">

    {% block stylesheets %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.css' %}">
    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <!--<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>-->
    {#<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">#}
    <!--[endif]-->

</head>
<body>
    <div class="container">
        {% block body %}
            {% block navbar %}
                <nav class="navbar navbar-default">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                            <a class="navbar-brand" href="{% url 'product:home' %}">Kiwi Catalog</a>
                        </div>
                        <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{% url 'product:category_list' %}">Products</a></li>
                            <li class="active"><a href="{% url 'product:recent_products' %}">Recent Products</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
                                {% load product_menu %}
                                {% product_menu %}
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'logout' %}">logout({{ user.username }})</a></li>
                            {% else %}
                                <li><a href="{% url 'login' %}">login</a></li>
                            {% endif %}
                      </ul>
                    </div><!--/.nav-collapse -->
                  </div>
                </nav>
            {% endblock %}


            {% load django_bootstrap_breadcrumbs %}
                {% block breadcrumbs %}
                    {% clear_breadcrumbs %}
                    {% breadcrumb "Home" "product:home" %}
                {% endblock %}

                {% render_breadcrumbs %}

            {% block content %}

            {% endblock %}

        {% endblock %}
    </div>

    {% block footer %}{% endblock %}

    {% block javascripts %}
        <script type="text/javascript" src='{% static 'jquery/dist/jquery.js' %}'></script>
        <script type="text/javascript" src='{% static 'bootstrap/dist/js/bootstrap.js' %}'></script>
    {% endblock %}

    <script>
        $(function() {
          {% block domready %}{% endblock %}
        });
    </script>

</body>
</html>

sources/product/templates/product/category_detail.html
{% extends 'product/base.html' %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Pruduct categories" "product:category_list" %}
    {% breadcrumb ""|add:category.name "product:category_detail" category.slug %}
{% endblock %}

{% block content %}

    <h1>{{ category.name }}</h1>
    <p>{{ category.description }}</p>

    <h3>products</h3>
    {% include 'product/_product_list.html' with products=category.products.all %}

    {% include 'product/_pagination.html' with items=category.products url='product:category_detail' slug=category.slug %}
{% endblock %}

sources/product/templates/product/category_list.html
{% extends 'product/base.html' %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Pruduct categoruis" "product:category_list" %}
{% endblock %}

{% block content %}

    <ul>
        {% for category in object_list %}
            <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a> <span>({{ category.products.count }})</span></li>
        {% endfor %}
    </ul>

    {% include 'product/_pagination.html' with items=object_list url='product:category_list' %}
{% endblock %}

sources/product/templates/product/product_detail.html
{% extends 'product/base.html' %}

{% load django_bootstrap_breadcrumbs %}
    {% block breadcrumbs %}
        {{ block.super }}
        {% breadcrumb "Pruduct categories" "product:category_list" %}
        {% breadcrumb ""|add:product.category.name "product:category_detail" product.category.slug %}
        {% breadcrumb ""|add:product.name "product:product_detail" product.category.slug product.slug %}
    {% endblock %}

{% block content %}



    id: {{ product.id }}<br>
    name: {{ product.name }}<br>
    created: {{ product.created_at }}<br>
{% endblock %}

sources/product/templates/product/product_menu.html
<ul class="dropdown-menu">
    {% for item in items %}
        <li><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></li>
    {% endfor %}
</ul>

sources/product/templates/product/recent_products.html
{% extends 'product/base.html' %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Recent pruducts" "product:recent_products" %}
{% endblock %}

{% block content %}

    <h1>Recent products</h1>

    {% include 'product/_product_list.html' %}

    {% include 'product/_pagination.html' with items=products url='product:recent_products' %}

{% endblock %}